# Generated by Django 5.0.3 on 2024-04-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('target', models.DecimalField(decimal_places=8, max_digits=20)),
                ('deadline', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=200)),
                ('to_address', models.CharField(max_length=200)),
                ('campaign_address', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('no_of_votes', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='elction_images')),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_metamask_id', models.CharField(max_length=200)),
                ('requester_name', models.CharField(max_length=100)),
                ('institutional_address', models.TextField(max_length=2000)),
                ('need', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_loan_images')),
                ('fund_needed', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='MetamaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metamask_id', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_metamask_id', models.CharField(max_length=200)),
                ('reviewer_name', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LoanInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator_metamask_id', models.CharField(max_length=200)),
                ('needy_name', models.CharField(max_length=100)),
                ('needy_metamask_id', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('loan_request_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meta_user_key', models.CharField(max_length=100)),
                ('election_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.election')),
            ],
        ),
    ]
