# Generated by Django 5.0.3 on 2024-03-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_election'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Election',
        ),
    ]
