# Generated by Django 5.0.3 on 2024-03-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_election"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="elction_images"),
        ),
        migrations.AddField(
            model_name="election",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="no_of_votes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="owner",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mete_user_key", models.CharField(max_length=100)),
                (
                    "election_foreign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.election"
                    ),
                ),
                (
                    "user_foreign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.metamaskuser",
                    ),
                ),
            ],
        ),
    ]
