# Generated by Django 5.0.3 on 2024-03-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_election_description_election_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
