# Generated by Django 5.0.3 on 2024-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_election_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
